[package]
name = "symbolize-lib-hex"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/mod.rs"

[dependencies]
anyhow = { workspace = true }

[lints]
workspace = true
