[advisories]
db-path = "build/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "deny"

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "MIT", "Unicode-DFS-2016"]
default = "deny"
confidence-threshold = 0.8

[licenses.private]
ignore = true

[bans]
multiple-versions = "deny"
wildcards = "deny"

[[bans.skip]]
name = "futures"
version = "=0.1.31"

[[bans.skip-tree]]
name = "redox_syscall"
version = "0.4.1"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index", "https://github.com/facebook/watchman"]
allow-git = []

[sources.allow-org]
github = []
gitlab = []
bitbucket = []
