packages:
  - dev-esbuild
  - dev-eslint
  - dev-node-loader
  - dev-node-suppress
  - dev-pnpm-test
  - dev-prettier
  - dev-tsconfig
  - lib-collection
  - lib-concurrency
  - lib-dataflow
  - lib-error
  - lib-hex-ts
  - lib-markup
  - lib-payload
  - lib-random
  - lib-stream
  - lib-styling
  - lib-test
  - lib-test-runner
  - lib-time
  - svc-auth-guest-read
  - svc-auth-guest-view
  - svc-gateway-guest-run
