packages:
  - dev-esbuild
  - dev-eslint
  - dev-node-loader
  - dev-node-suppress
  - dev-pnpm-test
  - dev-prettier
  - dev-tsconfig
  - lib-concurrency
  - lib-crypto
  - lib-error
  - lib-hex
  - lib-random
  - lib-stream
  - lib-style
  - lib-test
  - lib-time
  - lib-widget
  - svc-auth-guest-display
  - svc-gateway-guest
