[tool.sqlfluff.core]
dialect = "sqlite"
templater = "placeholder"
sql_file_exts = ".sql"
max_line_length = 60
processes = -1

[tool.sqlfluff.templater.placeholder]
param_style = "colon"

[tool.sqlfluff.indentation]
tab_space_size = 2

[tool.sqlfluff.rules.aliasing.table]
aliasing = "explicit"

[tool.sqlfluff.rules.aliasing.column]
aliasing = "explicit"

[tool.sqlfluff.rules.aliasing.length]
min_alias_length = 3

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.identifiers]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = "lower"

[tool.sqlfluff.rules.capitalisation.types]
extended_capitalisation_policy = "lower"

[tool.sqlfluff.rules.convention.terminator]
require_final_semicolon = true
