resolver:
  # https://www.stackage.org/lts-21.11
  lts-21.11

packages:
  - dev-gen
  - dev-stack-bin

extra-deps:
  - algebraic-graphs-0.6.1
  - ansi-terminal-0.11.5
  - floskell-0.10.8
  - ghcide-2.2.0.0
  - haskell-language-server-2.2.0.0
  - hie-compat-0.3.1.1
  - hiedb-0.4.3.0
  - hls-alternate-number-format-plugin-2.2.0.0
  - hls-cabal-fmt-plugin-2.2.0.0
  - hls-cabal-plugin-2.2.0.0
  - hls-call-hierarchy-plugin-2.2.0.0
  - hls-change-type-signature-plugin-2.2.0.0
  - hls-class-plugin-2.2.0.0
  - hls-code-range-plugin-2.2.0.0
  - hls-eval-plugin-2.2.0.0
  - hls-explicit-fixity-plugin-2.2.0.0
  - hls-explicit-imports-plugin-2.2.0.0
  - hls-explicit-record-fields-plugin-2.2.0.0
  - hls-floskell-plugin-2.2.0.0
  - hls-fourmolu-plugin-2.2.0.0
  - hls-gadt-plugin-2.2.0.0
  - hls-graph-2.2.0.0
  - hls-hlint-plugin-2.2.0.0
  - hls-module-name-plugin-2.2.0.0
  - hls-ormolu-plugin-2.2.0.0
  - hls-overloaded-record-dot-plugin-2.2.0.0
  - hls-plugin-api-2.2.0.0
  - hls-pragmas-plugin-2.2.0.0
  - hls-qualify-imported-names-plugin-2.2.0.0
  - hls-refactor-plugin-2.2.0.0
  - hls-rename-plugin-2.2.0.0
  - hls-retrie-plugin-2.2.0.0
  - hls-splice-plugin-2.2.0.0
  - hw-fingertree-0.1.2.1
  - hw-prim-0.6.3.2
  - implicit-hie-0.1.2.7
  - implicit-hie-cradle-0.5.0.1
  - monad-dijkstra-0.1.1.3
  - retrie-1.2.2
  - lsp-2.2.0.0
  - lsp-test-0.16.0.0
  - lsp-types-2.0.2.0

flags:
  haskell-language-server:
    stylishHaskell: false

local-bin-path: ./.stack-bin

ghc-options:
  "$everything": >
    -O2
  "$targets": >
    -O0
    -g2
    -threaded
    -Weverything
    -Wno-missing-safe-haskell-mode
    -Wno-orphans
    -Wno-unsafe
    -Wno-unused-packages
    -Wno-all-missed-specialisations

rebuild-ghc-options: true

system-ghc: true

install-ghc: false
  
nix:
  enable: false
