includes:
  cargo:
    taskfile: dev-task/cargo.yml
  dev-esbuild:
    taskfile: dev-esbuild
  dev-eslint:
    taskfile: dev-eslint
  dev-gen:
    taskfile: dev-gen
  dev-nix-shell:
    internal: true
    taskfile: dev-nix-shell
  dev-node-loader:
    taskfile: dev-node-loader
  dev-node-suppress:
    taskfile: dev-node-suppress
  dev-pnpm-test:
    taskfile: dev-pnpm-test
  dev-prettier:
    taskfile: dev-prettier
  dev-stack-bin:
    internal: true
    taskfile: dev-stack-bin
  dev-tsconfig:
    taskfile: dev-tsconfig
  lib-concurrency:
    taskfile: lib-concurrency
  lib-error:
    taskfile: lib-error
  lib-hex:
    taskfile: lib-hex
  lib-random:
    taskfile: lib-random
  lib-style:
    taskfile: lib-style
  lib-test:
    taskfile: lib-test
  lib-time:
    taskfile: lib-time
  lib-widget:
    taskfile: lib-widget
  nix:
    taskfile: dev-task/nix.yml
  pnpm:
    taskfile: dev-task/pnpm.yml
  stack:
    taskfile: dev-task/stack.yml
  svc-auth-guest-display:
    taskfile: svc-auth-guest-display
  svc-gateway-guest:
    taskfile: svc-gateway-guest
  tmpfs:
    taskfile: dev-task/tmpfs.yml
run: when_changed
tasks:
  build:debug:
    aliases:
      - build
      - b
    deps:
      - cargo:build:debug
      - pnpm:build:debug
      - stack:build:debug
  build:release:
    aliases:
      - br
    deps:
      - cargo:build:release
      - pnpm:build:release
      - stack:build:release
  check:
    aliases:
      - c
    deps:
      - build:release
      - gen:check
      - test:release
      - format:check
      - lint:check
      - lock:check
  clean:
    deps:
      - cargo:clean
      - pnpm:clean
      - stack:clean
  format:check:
    aliases:
      - fc
    deps:
      - stack:format:check
  format:fix:
    aliases:
      - format
      - f
    deps:
      - pnpm:format:fix
      - stack:format:fix
  gen:
    aliases:
      - g
    cmd:
      task: stack:execute-target
      vars:
        MODE: release
        NAME: dev-gen
        TARGET: exe
    deps:
      - stack:build:release
  gen:check:
    cmd:
      task: stack:execute-target
      vars:
        ARGS: --check
        MODE: release
        NAME: dev-gen
        TARGET: exe
    deps:
      - stack:build:release
  install:
    aliases:
      - i
    deps:
      - cargo:install
      - stack:install
  lint:check:
    aliases:
      - lint
      - l
    deps:
      - pnpm:lint:check
      - stack:lint:check
  lint:fix:
    aliases:
      - lf
    deps:
      - pnpm:lint:fix
      - stack:lint:check
  lock:check:
    deps:
      - cargo:lock:check
      - pnpm:lock:check
  pnpm:eslint:lint:check:
    cmd:
      task: pnpm:eslint:lint-folders:check
      vars:
        NAMES: '{{.PNPM_TYPESCRIPT_PACKAGES}}'
    deps:
      - pnpm:tsc:build
  pnpm:eslint:lint:fix:
    cmd:
      task: pnpm:eslint:lint-folders:fix
      vars:
        NAMES: '{{.PNPM_TYPESCRIPT_PACKAGES}}'
    deps:
      - pnpm:tsc:build
  pnpm:link-build-dirs:
    deps:
      - dev-esbuild:link-build-dir
      - dev-eslint:link-build-dir
      - dev-node-loader:link-build-dir
      - dev-node-suppress:link-build-dir
      - dev-pnpm-test:link-build-dir
      - dev-prettier:link-build-dir
      - dev-tsconfig:link-build-dir
      - lib-concurrency:link-build-dir
      - lib-error:link-build-dir
      - lib-hex:link-build-dir
      - lib-random:link-build-dir
      - lib-style:link-build-dir
      - lib-test:link-build-dir
      - lib-time:link-build-dir
      - lib-widget:link-build-dir
      - svc-auth-guest-display:link-build-dir
      - svc-gateway-guest:link-build-dir
  pnpm:lint:check:
    deps:
      - pnpm:syncpack:lint:check
      - pnpm:eslint:lint:check
  pnpm:lint:fix:
    deps:
      - pnpm:syncpack:lint:check
      - pnpm:eslint:lint:fix
  stack:format:check:
    cmd:
      task: stack:format-folders:check
      vars:
        NAMES: '{{.STACK_PACKAGES}}'
  stack:format:fix:
    cmd:
      task: stack:format-folders:fix
      vars:
        NAMES: '{{.STACK_PACKAGES}}'
  stack:link-build-dirs:
    deps:
      - dev-gen:link-build-dir
  stack:lint:check:
    cmd:
      task: stack:lint-folders:check
      vars:
        NAMES: '{{.STACK_PACKAGES}}'
  test:release:
    aliases:
      - tr
    deps:
      - cargo:test:release
      - pnpm:test
      - stack:test:release
  tmpfs:link-build-dirs:
    cmd:
      task: tmpfs:link-package-build-dirs
    deps:
      - tmpfs:link-root-build-dir
  tmpfs:link-package-build-dirs:
    deps:
      - pnpm:link-build-dirs
      - stack:link-build-dirs
vars:
  PNPM_TYPESCRIPT_PACKAGES:
    dev-esbuild dev-node-loader dev-node-suppress dev-pnpm-test
    lib-concurrency lib-error lib-hex lib-random lib-style lib-test lib-time lib-widget
    svc-auth-guest-display svc-gateway-guest
  STACK_PACKAGES: dev-gen
version: '3'
