version: '3'
  
run: when_changed
  
includes:
  cargo:
    taskfile: dev-task/Cargo.yml
    dir: .

  nix:
    taskfile: dev-task/Nix.yml
    dir: .

  stack:
    taskfile: dev-task/Stack.yml
    dir: .

  dev-gen:
    taskfile: dev-gen
    dir: dev-gen

  dev-cargo-bin:
    internal: true
    taskfile: dev-cargo-bin
    dir: dev-cargo-bin

  dev-nix-shell:
    internal: true
    taskfile: dev-nix-shell
    dir: dev-nix-shell

  dev-stack-bin:
    internal: true
    taskfile: dev-stack-bin
    dir: dev-stack-bin

tasks:
  build:
    deps:
      - stack:build
  
  install:
    deps:
      - stack:install
      - cargo:install
