version: '3'
  
run: when_changed
  
includes:
  dev-gen:
    taskfile: dev-gen
    dir: dev-gen

  dev-cargo-bin:
    taskfile: dev-cargo-bin
    dir: dev-cargo-bin

  dev-nix-shell:
    taskfile: dev-nix-shell
    dir: dev-nix-shell

  dev-stack-bin:
    taskfile: dev-stack-bin
    dir: dev-stack-bin

tasks:
  build:
    deps:
      - stack:build
  
  install:
    deps:
      - dev-stack-bin:install
      - dev-cargo-bin:install

  stack:build:
    cmd: stack build --test --no-run-tests

  stack:build:watch:
    cmd: stack build --test --no-run-tests --file-watch
      
  cargo:lock:
    cargo metadata --format-version=1 >/dev/null
      
  cargo:lock:check:
    cargo metadata --frozen --format-version=1 >/dev/null
