version: '3'
  
run: when_changed
  
includes:
  dev-gen:
    taskfile: dev-gen
    dir: dev-gen

  dev-cargo-bin:
    taskfile: dev-cargo-bin
    dir: dev-cargo-bin

  dev-nix-shell:
    taskfile: dev-nix-shell
    dir: dev-nix-shell

tasks:
  build:
    deps:
      - build:stack

  build:stack:
    cmd: stack build

  stack:build:watch:
    cmd: stack build --test --no-run-tests --file-watch
      
  cargo:lock:
    cargo metadata --format-version=1 >/dev/null
      
  cargo:lock:check:
    cargo metadata --frozen --format-version=1 >/dev/null
