includes:
  cargo:
    taskfile: dev-task/cargo.yml
  dev-esbuild:
    taskfile: dev-esbuild
  dev-eslint:
    taskfile: dev-eslint
  dev-gen:
    taskfile: dev-gen
  dev-nix-shell:
    internal: true
    taskfile: dev-nix-shell
  dev-node-loader:
    taskfile: dev-node-loader
  dev-node-suppress:
    taskfile: dev-node-suppress
  dev-pnpm-test:
    taskfile: dev-pnpm-test
  dev-prettier:
    taskfile: dev-prettier
  dev-stack-bin:
    internal: true
    taskfile: dev-stack-bin
  dev-tsconfig:
    taskfile: dev-tsconfig
  lib-collection:
    taskfile: lib-collection
  lib-concurrency:
    taskfile: lib-concurrency
  lib-error:
    taskfile: lib-error
  lib-hex:
    taskfile: lib-hex
  lib-payload:
    taskfile: lib-payload
  lib-random:
    taskfile: lib-random
  lib-style:
    taskfile: lib-style
  lib-test:
    taskfile: lib-test
  lib-time:
    taskfile: lib-time
  lib-widget:
    taskfile: lib-widget
  nix:
    taskfile: dev-task/nix.yml
  pnpm:
    taskfile: dev-task/pnpm.yml
  sqlite:
    taskfile: dev-task/sqlite.yml
  stack:
    taskfile: dev-task/stack.yml
  svc-auth-guest-read:
    taskfile: svc-auth-guest-read
  svc-auth-guest-view:
    taskfile: svc-auth-guest-view
  svc-gateway-guest-run:
    taskfile: svc-gateway-guest-run
  svc-gateway-host-run:
    taskfile: svc-gateway-host-run
  svc-gateway-host-store:
    taskfile: svc-gateway-host-store
  svc-search-host-read:
    taskfile: svc-search-host-read
  tmpfs:
    taskfile: dev-task/tmpfs.yml
run: when_changed
tasks:
  build:debug:
    aliases:
      - build
      - b
    deps:
      - cargo:build:debug
      - pnpm:build:debug
      - stack:build:debug
  build:release:
    aliases:
      - br
    deps:
      - cargo:build:release
      - pnpm:build:release
      - stack:build:release
  check:
    aliases:
      - c
    deps:
      - build:release
      - gen:check
      - test:release
      - format:check
      - lint:check
      - lock:check
  clean:
    deps:
      - cargo:clean
      - pnpm:clean
      - stack:clean
  format:check:
    aliases:
      - fc
    deps:
      - cargo:format:check
      - pnpm:format:check
      - stack:format:check
  format:fix:
    aliases:
      - format
      - f
    deps:
      - cargo:format:fix
      - pnpm:format:fix
      - stack:format:fix
  gen:
    aliases:
      - g
    cmd:
      task: stack:execute-target
      vars:
        MODE: release
        NAME: dev-gen
        TARGET: exe
    deps:
      - stack:build:release
  gen:check:
    cmd:
      task: stack:execute-target
      vars:
        ARGS: --check
        MODE: release
        NAME: dev-gen
        TARGET: exe
    deps:
      - stack:build:release
  install:
    aliases:
      - i
    deps:
      - cargo:install
      - stack:install
  lint:check:
    aliases:
      - lint
      - l
    deps:
      - cargo:lint:check
      - pnpm:lint:check
      - sqlite:lint:check
      - stack:lint
  lint:fix:
    aliases:
      - lf
    deps:
      - cargo:lint:fix
      - pnpm:lint:fix
      - sqlite:lint:fix
      - stack:lint
  lock:check:
    deps:
      - cargo:lock:check
      - pnpm:lock:check
  pnpm:link-build-dirs:
    deps:
      - dev-esbuild:link-build-dir
      - dev-eslint:link-build-dir
      - dev-node-loader:link-build-dir
      - dev-node-suppress:link-build-dir
      - dev-pnpm-test:link-build-dir
      - dev-prettier:link-build-dir
      - dev-tsconfig:link-build-dir
      - lib-collection:link-build-dir
      - lib-concurrency:link-build-dir
      - lib-error:link-build-dir
      - lib-hex:link-build-dir
      - lib-payload:link-build-dir
      - lib-random:link-build-dir
      - lib-style:link-build-dir
      - lib-test:link-build-dir
      - lib-time:link-build-dir
      - lib-widget:link-build-dir
      - svc-auth-guest-read:link-build-dir
      - svc-auth-guest-view:link-build-dir
      - svc-gateway-guest-run:link-build-dir
  test:release:
    aliases:
      - tr
    deps:
      - cargo:test:release
      - pnpm:test
      - stack:test:release
version: '3'
