[package]
name = "intertwine-svc-gateway-host-run"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
headers = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
mime = { workspace = true }
rusqlite = { workspace = true }
self_cell = { workspace = true }
tokio = { workspace = true }
