version: '3'

run: when_changed

vars:
  NAME: svc-gateway-host-run

tasks:
  run:debug:
    aliases:
      - run
      - r
    cmd:
      task: :cargo:execute-package
      vars:
        RELEASE: false
        NAME: '{{.NAME}}'

  run:debug:watch:
    aliases:
      - run:watch
      - rw
    cmd:
      task: :cargo:execute-package:watch
      vars:
        RELEASE: false
        NAME: '{{.NAME}}'

  run:release:
    aliases:
      - rr
    cmd:
      task: :cargo:execute-package
      vars:
        RELEASE: true
        NAME: '{{.NAME}}'
