version: '3'

run: when_changed

vars:
  NAME: dev-gen

tasks:
  repl:debug:
    aliases:
      - repl
    cmd:
      task: :stack:repl:debug
      vars:
        NAME: '{{.NAME}}'

  repl:release:
    cmd:
      task: :stack:repl:release
      vars:
        NAME: '{{.NAME}}'

  test:debug:
    aliases:
      - test
      - t
    cmd:
      task: :stack:execute-target:test:debug
      vars:
        NAME: '{{.NAME}}'

  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmd:
      task: :stack:execute-target:test:debug:watch
      vars:
        NAME: '{{.NAME}}'

  test:release:
    aliases:
      - tr
    cmd:
      task: :stack:execute-target:test:release
      vars:
        NAME: '{{.NAME}}'

  link-build-dir:
    cmd:
      task: :tmpfs:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
