version: '3'

run: when_changed

vars:
  NAME: dev-gen

tasks:
  repl:
    cmd:
      task: :stack:repl
      vars:
        NAME: '{{.NAME}}'

  run:debug:
    aliases:
      - run
      - r
    cmd:
      task: :stack:execute-target
      vars:
        MODE: debug
        NAME: '{{.NAME}}'
        TARGET: exe

  run:release:
    aliases:
      - rr
    cmd:
      task: :stack:execute-target
      vars:
        MODE: debug
        NAME: '{{.NAME}}'
        TARGET: exe

  run:debug:watch:
    aliases:
      - run:watch
      - rw
    cmd:
      task: :stack:execute-target:watch
      vars:
        MODE: debug
        NAME: '{{.NAME}}'
        TARGET: exe

  test:debug:
    aliases:
      - test
      - t
    cmd:
      task: :stack:execute-target
      vars:
        MODE: debug
        NAME: '{{.NAME}}'
        TARGET: test

  test:release:
    aliases:
      - tr
    cmd:
      task: :stack:execute-target
      vars:
        MODE: release
        NAME: '{{.NAME}}'
        TARGET: test

  test:debug:watch:
    aliases:
      - test:watch
      - tw
    cmd:
      task: :stack:execute-target:watch
      vars:
        MODE: debug
        NAME: '{{.NAME}}'
        TARGET: test

  link-build-dir:
    cmd:
      task: :tmpfs:link-package-build-dir
      vars:
        NAME: '{{.NAME}}'
