version: '3'
  
run: when_changed
  
includes:
  stack:
    internal: true
    taskfile: ../dev-task/Stack.yml
    dir: .

vars:
  NAME: dev-gen

tasks:
  format:
    cmd:
      task: stack:format

  format:check:
    cmd:
      task: stack:format:check

  lint:
    cmd:
      task: stack:lint

  repl:
    cmd:
      task: stack:repl-target
      vars:
        TARGET: intertwine-{{.NAME}}

  run:
    aliases:
      - r
    cmd:
      task: stack:execute-target
      vars:
        TARGET: intertwine-{{.NAME}}-exe

  run:watch:
    aliases:
      - rw
    cmd:
      task: stack:execute-target:watch
      vars:
        TARGET: intertwine-{{.NAME}}-exe

  test:
    aliases:
      - t
    cmd:
      task: stack:execute-target
      vars:
        TARGET: intertwine-{{.NAME}}-test

  test:watch:
    aliases:
      - tw
    cmd:
      task: stack:execute-target:watch
      vars:
        TARGET: intertwine-{{.NAME}}-test
