version: '3'
  
run: when_changed
  
includes:
  stack:
    internal: true
    taskfile: ../dev-task/Stack.yml
    dir: .

tasks:
  repl:
    cmd:
      task: stack:repl-target
      vars:
        TARGET: intertwine-dev-gen

  run:
    cmd:
      task: stack:execute-target
      vars:
        TARGET: intertwine-dev-gen-exe

  run:watch:
    cmd:
      task: stack:execute-target:watch
      vars:
        TARGET: intertwine-dev-gen-exe

  test:
    cmd:
      task: stack:execute-target
      vars:
        TARGET: intertwine-dev-gen-test

  test:watch:
    cmd:
      task: stack:execute-target:watch
      vars:
        TARGET: intertwine-dev-gen-test
