version: '3'

run: when_changed

vars:
  NAME: dev-gen

tasks:
  repl:
    cmd:
      task: :stack:repl
      vars:
        NAME: '{{.NAME}}'

  run:
    aliases:
      - r
    cmd:
      task: :stack:run
      vars:
        NAME: '{{.NAME}}'

  run:watch:
    aliases:
      - rw
    cmd:
      task: :stack:run:watch
      vars:
        NAME: '{{.NAME}}'

  test:
    aliases:
      - t
    cmd:
      task: :stack:test
      vars:
        NAME: '{{.NAME}}'

  test:watch:
    aliases:
      - tw
    cmd:
      task: :stack:test:watch
      vars:
        NAME: '{{.NAME}}'
