version: '3'
  
run: when_changed
  
tasks:
  clean:
    cmd: stack clean --full

  install:
    deps:
      - :dev-stack-bin:install

  build:debug:
    aliases:
      - build
      - b
    cmd: stack build --test --no-run-tests --keep-going

  build:release:
    aliases:
      - br
    cmd: stack build --test --no-run-tests --keep-going --ghc-options "-O2 -g0 -Werror"

  build:debug:watch:
    aliases:
      - build:watch
      - bw
    cmd: stack build --test --no-run-tests --keep-going --file-watch

  format:
    internal: true
    cmd: ormolu --mode inplace $(find app src test -name '*.hs')

  format:check:
    internal: true
    cmd: ormolu --mode check $(find app src test -name '*.hs')

  lint:
    internal: true
    cmd: hlint --hint $(realpath --relative-to . {{.STACK_LOCAL_BIN_PATH}}/relude-hlint.yaml) --hint ../dev-hlint/base.yaml --threads app src test

  repl-target:
    internal: true
    requires:
      vars:
        - TARGET
    cmd: stack ghci {{.TARGET}}
  
  execute-target:
    internal: true
    requires:
      vars:
        - TARGET
    vars:
      DIST_DIR:
        sh: realpath --relative-to . $(sh -c "$(stack config env) echo \$HASKELL_DIST_DIR")
    cmd: "{{.DIST_DIR}}/build/{{.TARGET}}/{{.TARGET}}"
  
  execute-target:watch:
    internal: true
    requires:
      vars:
        - TARGET
    vars:
      DIST_DIR:
        sh: realpath --relative-to . $(sh -c "$(stack config env) echo \$HASKELL_DIST_DIR")
    cmd: watchexec --no-vcs-ignore --watch {{.DIST_DIR}}/build/{{.TARGET}}/{{.TARGET}} -- {{.DIST_DIR}}/build/{{.TARGET}}/{{.TARGET}}
