name: FTS

on:
  push:
    paths:
      - "*"
      - .github/**
      - db/**
      - fts/**

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly
        if: github.ref == 'refs/heads/main'
        run: |
          curl -fsSL https://fly.io/install.sh | sudo FLYCTL_INSTALL=/usr/local sh

      - name: Cache Rust toolchain
        uses: actions/cache@v2
        with:
          path: /usr/share/rust/.rustup
          key: rust-toolchain-1

      - name: Set up Rust
        run: rustup show
      
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: Check rustfmt
        run: cargo fmt --all -- --check

      - name: Check rustc
        if: github.ref != 'refs/heads/main'
        run: cargo check

      - name: Build
        if: github.ref == 'refs/heads/main'
        run: cargo build --release
