name: Main

on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly
        if: github.ref == 'refs/heads/action'
        run: |
          curl -L https://fly.io/install.sh | sudo FLYCTL_INSTALL=/usr/local sh

      - name: Set up Dbmate
        run: |
          sudo curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          sudo chmod +x /usr/local/bin/dbmate

      - name: Set up direnv
        run: |
          sudo apt-get install direnv
          echo > .env
          direnv allow

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('./pnpm-lock.yaml') }}

      - name: Set up pnpm
        run: |
          npm i -g pnpm
          pnpm install --frozen-lockfile

      - name: Check Prettier
        run: pnpm check-prettier

      - name: Check ESLint
        run: pnpm check-eslint

      - name: Check TypeScript
        run: pnpm check-tsc

      - name: Test
        run: direnv exec . pnpm test

      - name: Build
        run: direnv exec . pnpm build

      - name: Prune
        if: github.ref == 'refs/heads/action'
        run: pnpm prune --prod

      - name: Deploy
        if: github.ref == 'refs/heads/action'
        run: direnv exec . flyctl deploy --build-arg NODE_OPTIONS="${NODE_OPTIONS_PRODUCTION}"
        env:
          FLY_ACCESS_TOKEN: ${{ secrets.FLY_ACCESS_TOKEN }}
